### ISSUE TITLE
Missing Example when running CLI command

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#301]
My guess is that the notebooks need to be included in MANIFEST.in file

### REPRODUCTION

```
conda create -n test-xarray-spatial python=3.7
conda activate test-xarray-spatial
pip install xarray-spatial
xrspatial examples
```

When testing, you should trying install xarray-spatial in a fresh environment directly from github branch (https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch):

```
pip install https://github.com/user/repository/archive/branch.zip
```

### Trace
```
(test-xarray-spatial) ➜  xarray-spatial git:(master) xrspatial examples
Traceback (most recent call last):
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/bin/xrspatial", line 8, in <module>
    sys.exit(main())
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/xrspatial/__main__.py", line 11, in main
    return pyct.cmd.substitute_main('xrspatial',args=args)
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/pyct/cmd.py", line 455, in substitute_main
    args.func(args) if hasattr(args,'func') else parser.error("must supply command to run")
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/pyct/cmd.py", line 394, in <lambda>
    parser.set_defaults(func=lambda args: fn(name, **{k: getattr(args,k) for k in vars(args) if k!='func'} ))
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/pyct/cmd.py", line 38, in examples
    copy_examples(name, path, verbose, force)
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/pyct/cmd.py", line 44, in copy_examples
    source = _find_examples(name)
  File "/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/pyct/cmd.py", line 28, in _find_examples
    raise ValueError("Could not find examples for %s at any of %s"%(name,candidates))
ValueError: Could not find examples for xrspatial at any of ['/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/xrspatial/examples', '/Users/brendan/miniconda3/envs/test-xarray-spatial/lib/python3.7/site-packages/xrspatial/../examples']
```

**Comment by giancastro** [comment]
@lex-c, has this issue already solved?
